exclude: (^proto/|yoctolib/)
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        args:
          [
            '--max-line-length=88',
            '--ignore=E203,E501,W503',
            '--per-file-ignores=__init__.py:F401',
          ]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        args:
          [
            '--line-width',
            '88',
            '--multi-line',
            '3',
            '--trailing-comma',
            '--use-parentheses',
          ]
        additional_dependencies: [toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--config-file=sread/mypy.ini]
        additional_dependencies: [typer==0.2.1]
