[tool.poetry]
name = "project"
version = "0.1.0"
description = ""
authors = ["Niklas Sturm"]

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.5.0"
aiohttp = "^3.6.2"
pandas = "^1.0.3"
spacy = "^2.2.4"
beautifulsoup4 = "^4.9.1"
lxml = "^4.5.0"
tika = "^1.24"
typer = "^0.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.2"
black = "^19.10b0"
ipykernel = "^5.2.1"
bandit = "^1.6.2"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
